Config.MDT = {
    General = {
        -- This will be displayed on the top left corner of the mdt
        Title = "Masons World Mobile Data Terminal",

        -- This will allow the police the ability to jail people automatically after submitting an arrest report
        JailButton = false,

        -- Setting this to true will automatically check, or enable, players automatically being sent to jail. (This is in case officers forget to check this off when making an arrest report)
        -- False = Checkbox will be unchecked by default | True = Checkbox will be checked by default
        JailButtonActiveDefault = false,

        -- ONLY APPLICABLE IF "JailButton" IS TRUE. This will require police to put in a reason for jailing -- this way when the player is jailed, it will provide a reason to a jailing script.
        JailReason = true,
    },

    -- Options given when filling out an incident report...not to be confused with the arrest report
    incidentResultTypes = {
        "Fined",
        "Written Warning",
        "Not Applicable",
        "Other"
    },

    CustomTabs = {
        -- Label will be displayed in the navigation bar at the top of the mdt
        -- The link will be the site displayed when the tab is active
        -- NOTE: You may have ONLY 3 custom tabs, adding more will NOT result in more custom tabs;
        -- ALSO, if you aren't seeing the tabs appear, check the permissions (found below in this file -- they're all set to false by default)
        {
            enabled = false,
            label = "Label 1",
            link = "https://store.aljunier-development.com/"
        },
        {
            enabled = false,
            label = "Label 2",
            link = "https://store.aljunier-development.com/"
        },
        {
            enabled = false,
            label = "Label 3",
            link = "https://store.aljunier-development.com/"
        },
    },

    -- Labels given for licenes
    LicenseLabels = {
        -- ESX
        boat        = "Boating License",
        drive       = "Driver's License",
        drive_bike  = "Motorcycle License",
        drive_truck = "Commercial Driver's License",
        weapon      = "Firearm License",

        -- QBCore
        driver      = "Driver's License",
        business    = "Business License",
    },

    GrantableLicenses  = {
        -- Add the id of any license you want to be granted (more than one can be added)
        -- Note: The label of the license has to be filled in the table above, or else the name will appear as the license id
        'weapon',
    },

    Jobs = {
        {
            type = "police", -- Dont change this
            job = "police", -- You can change this to the appropriate job reflected by your server
        },
        {
            type = "ems", -- Dont change this
            job = "ambulance", -- You can change this to the appropriate job reflected by your server
        },
        {
            type = "roadside", -- Dont change this
            job = "mechanic", -- You can change this to the appropriate job reflected by your server
        },
        {
            type = "doj", -- Dont change this
            job = "doj", -- You can change this to the appropriate job reflected by your server
        },
    },

    Permissions = {
        police = {
            units = {
                tab = true,
                police = {
                    gps = true,
                    copyStatus = true,
                    changeStatus = true,
                },
                ems = {
                    gps = true,
                    copyStatus = true,
                    changeStatus = false,
                },
                roadside = {
                    gps = false,
                    copyStatus = true,
                    changeStatus = false,
                },
            },
            bolos = {
                tab = true,
                create = true,
                edit = true,
                delete = true,
            },
            warrants = {
                tab = true,
                create = true,
                edit = true,
                delete = true,
            },
            database = {
                search = true, -- Tab only
                createReport = true, -- Tab only (however setting this to false will mean that reports can't be created)
                viewReport = true -- Tab only
            },
            activity = true,
            customTabs = {
                tab1 = false,
                tab2 = false,
                tab3 = false,
            },
            clockin = true,
            reports = {
                edit = true,
                delete = true,
            },
            profiles = {
                civ = { -- All false means they can only view and not edit
                    editContact = true,
                    revokeLicenses = true,
                    grantLicenses = true,
                    exemptFines = true,
                    editNotes = true,
                    editPhotoID = true,
                },
                veh = { -- All false means they can only view and not edit
                    editPhoto = true,
                    editNotes = true,
                    editVehicleInfo = true,
                },
            },
        },
        ems = {
            units = {
                tab = true,
                police = {
                    gps = true,
                    copyStatus = true,
                    changeStatus = false,
                },
                ems = {
                    gps = true,
                    copyStatus = true,
                    changeStatus = true,
                },
                roadside = {
                    gps = false,
                    copyStatus = true,
                    changeStatus = false,
                },
            },
            bolos = {
                tab = false,
                create = false,
                edit = false,
                delete = false,
            },
            warrants = {
                tab = false,
                create = false,
                edit = false,
                delete = false,
            },
            database = {
                search = false, -- Tab only
                createReport = false, -- Tab only (however setting this to false will mean that reports can't be created)
                viewReport = false -- Tab only
            },
            activity = true,
            customTabs = {
                tab1 = false,
                tab2 = false,
                tab3 = false,
            },
            clockin = true,
            reports = {
                edit = false,
                delete = false,
            },
            profiles = {
                civ = { -- All false means they can only view and not edit
                    editContact = false,
                    revokeLicenses = false,
                    grantLicenses = false,
                    exemptFines = false,
                    editNotes = false,
                    editPhotoID = false,
                },
                veh = { -- All false means they can only view and not edit
                    editPhoto = false,
                    editNotes = false,
                    editVehicleInfo = false,
                },
            },
        },
        roadside = {
            units = {
                tab = true,
                police = false,
                ems = false,
                roadside = {
                    gps = true,
                    copyStatus = true,
                    changeStatus = true,
                },
            },
            bolos = {
                tab = false,
                create = false,
                edit = false,
                delete = false,
            },
            warrants = {
                tab = false,
                create = false,
                edit = false,
                delete = false,
            },
            database = {
                search = false, -- Tab only
                createReport = false, -- Tab only (however setting this to false will mean that reports can't be created)
                viewReport = false -- Tab only
            },
            activity = true,
            customTabs = {
                tab1 = false,
                tab2 = false,
                tab3 = false,
            },
            clockin = true,
            reports = {
                edit = false,
                delete = false,
            },
            profiles = {
                civ = { -- All false means they can only view and not edit
                    editContact = false,
                    revokeLicenses = false,
                    grantLicenses = false,
                    exemptFines = false,
                    editNotes = false,
                    editPhotoID = false,
                },
                veh = { -- All false means they can only view and not edit
                    editPhoto = false,
                    editNotes = false,
                    editVehicleInfo = false,
                },
            },
        },
        doj = {
            units = {
                tab = false,
                police = false,
                ems = false,
                roadside = false,
            },
            bolos = {
                tab = true,
                create = false,
                edit = false,
                delete = false,
            },
            warrants = {
                tab = true,
                create = false,
                edit = false,
                delete = false,
            },
            database = {
                search = true, -- Tab only
                createReport = false, -- Tab only (however setting this to false will mean that reports can't be created)
                viewReport = true -- Tab only
            },
            activity = false,
            customTabs = {
                tab1 = false,
                tab2 = false,
                tab3 = false,
            },
            clockin = false,
            reports = {
                edit = false,
                delete = false,
            },
            profiles = {
                civ = { -- All false means they can only view and not edit
                    editContact = false,
                    revokeLicenses = false,
                    grantLicenses = false,
                    exemptFines = false,
                    editNotes = false,
                    editPhotoID = false,
                },
                veh = { -- All false means they can only view and not edit
                    editPhoto = false,
                    editNotes = false,
                    editVehicleInfo = false,
                },
            },
        },
    },

    Language = {
        dashboard = {
            term_dash = "Terminal Dashboard",
            act_units = "Active Units",
            act_bolo = "Active BOLOs/Warrants",
        },
        login = {
            term_login = "Terminal login",
            username = "Username",
            password = "Password",
            login = "Login",
            job = "Work Field",
            register = "Register",
            try_later = "Try again later",
            login_error = "Your login attempt had no response. Try again later",
            welcome = "Welcome",
            successful_login = "You signed in successfully",
            error = "Uh-oh!",
            error_msg_1 = "You are either not authorized to use this terminal or an error has occured during login.",
            error_msg_2 = "Your login could not be processed. Try again later",
        },
        activity = {
            title = "Shift Tracker",
            your_act = "Your activity",
            statistics = "Statistics",
            shift_log = "Shift Log",
            ["24hrs"] = "Last 24 hours",
            ["7days"] = "Last 7 days",
            total = "Total",
            col_1 = "ID",
            col_2 = "Clock-in",
            col_3 = "Clock-out",
            col_4 = "Duration",
            no_results = "No results found",
            other_act = "Others activity",
            user = "User",
            actions = "Actions",
            none = "None",
            more = "See more",
        },
        bolos = {
            title = "Bolos",
            register = "Register a bolo",
            voi = "Vehicle of interest",
            poi = "Person of interest",
            active = "Active BOLOs",
            entry_add = "Entry added",
            entry_add_msg = "Your bolo entry has been added!",
        },
        warrants = {
            title = "Warrants",
            register = "Register a warrant",
            active = "Active Warrants",
            entry_add = "Entry added",
            entry_add_msg = "Your warrant entry has been added!",
        },
        lookup = {
            title = "Database",
            title_2 = "Quick Search",
            title_3 = "Database Search",
            civ_search = "Civilian Search",
            plate_search = "License Plate Search",
        },
        reports = {
            title = "Database",
            title_2 = "Reports",
            title_3 = "Create a report",
            incident = "Create an incident report",
            arrest = "Create an arrest report",
        },
        view = {
            title = "Database",
            self_submit = "10 reports recently submitted by you",
            col_id = "ID",
            col_type = "Type",
            col_des = "Description",
            col_act = "Actions",
            col_date = "Date",
            col_sub = "Submitted By",
            search = "Search",
            clear = "Clear and refresh",
            view = "View",
            select = "Select",
            no_results = "No results found",
            type_none = "None",
            type_incident = "Incident",
            type_arrest = "Arrest",
            search_type = "Search by type",
            ph_search_type = "Search by type",
            search_name = "Search by name",
            ph_search_name = "Search by name",
            search_id = "Search by id",
            ph_search_id = "Search by id",
            filter = "Filter",
            title_2 = "Full report database",
            error_1 = "Unable to search",
            error_1_msg = "The search field(s) are either empty or an unexpected error has occured!",
            error_2 = "An error has occured",
            error_2_msg = "There was an issue while fetching this report, try again later",
        },
        nav = {
            nav_item_1 = "Dashboard",
            nav_item_2 = "Bolo",
            nav_item_3 = "Warrants",
            nav_item_4 = "Database",
            nav_item_4_1 = "Quick Search",
            nav_item_4_2 = "Create a report",
            nav_item_4_3 = "View reports",
            nav_item_5 = "Activity",
            nav_item_6_1 = "Notifcations",
            nav_item_6_2 = "Go on duty",
            nav_item_6_3 = "Go off duty",
            nav_item_6_4 = "Time on duty:",
            nav_item_6_5 = "Change patrol status",
            nav_item_6_6 = "Settings",
            nav_item_6_7 = "Logout",
            nav_close = "Close",
            error_1 = "Not authorized!",
            error_1_msg = "You are not authorized to use this terminal!",
            error_2 = "Unable to logout",
            error_2_msg = "You are still on-duty! Be sure to end your shift before logging out",
            logged_out = "Logged out",
            logged_out_msg = "You are still on-duty! Be sure to end your shift before logging out",
            clear_notif = "Notifications cleared",
            clear_notif_msg = "Your notifications were cleared!",
        },
        fines = {
            title = "Fines Dashboard",
            title_2 = "Unpaid fines",
            col_fine = "Fine",
            col_date = "Date of Offense",
            col_due = "Due date",
            col_act = "Actions",
            pay = "Pay",
            no_fines = "No fines to pay off!",
            success = "Success",
            success_msg_1 = "You paid off a $",
            success_msg_2 = "fine!",
            error_1 = "Not enough money",
            error_1_msg_1 = "You don't have $",
            error_1_msg_2 = "to pay this fine!",
            error_2 = "Uh-oh",
            error_2_msg = "An unexpected error has occured, try again later.",
        },
        viewbolo = {
            title_1 = "View Vehicle BOLO",
            title_2 = "View Person BOLO",
            title_3 = "View Warrant",
            title_4 = "View Bolo/Warrant",
            close = "Close",
            edit = "Edit",
            delete = "Delete",
            date_reg = "Date registered:",
            ref_num = "Reference Number:",
            col_sub = "Submitted by",
            col_veh = "Vehicle model",
            col_plate = "License plate",
            col_color = "Vehicle color",
            col_lastseen = "Last seen",
            col_vehdes = "Vehicle description",
            col_reason = "Reason for interest",
            col_notes = "Notes",
            col_name = "Name",
            col_des = "Description",
            not_avail = "Not available",
            none = "None",
        },
        editbolo = {
            title_1 = "Edit Vehicle BOLO",
            title_2 = "Edit Person BOLO",
            title_3 = "Edit Warrant",
            title_4 = "Edit Bolo/Warrant",
            close = "Close",
            edit = "Edit",
            delete = "Delete",
            date_reg = "Date registered:",
            ref_num = "Reference Number:",
            col_veh = "Vehicle model",
            col_plate = "License plate",
            col_color = "Vehicle color",
            col_lastseen = "Last seen",
            col_vehdes = "Vehicle description",
            col_reason = "Reason for interest",
            col_notes = "Notes",
            col_name = "Name",
            col_des = "Description",
            not_avail = "Not available",
            none = "None",
            discard = "Discard",
            save = "Save",
            saved = "Saved changes",
            saved_msg = "Your changes have been saved!",
        },
        affirmation = {
            title = "Are you sure?",
            no = "No",
            yes = "Yes",
        },
        changestatus = {
            changeplayerstatus = "Change player status for",
            title = "Select a status",
            unavail = "Unavailable",
            avail = "Available",
            busy = "Busy",
            oncall = "On Call",
            intran = "In Transport",
            panic = "Panic",
            close = "Close",
        },
        dutytoggle = {
            title_1 = "Clocking out",
            title_2 = "Clocking in",
            setcall = "Set your callsign before going on duty",
            clockin = "Go on duty",
            clockout = "Go off duty",
            elapsedtime = "Elapsed time on current shift",
            clockoutconfirm = "Are you sure you want to clock out?",
            close = "Close",
            clockedin = "You're on duty!",
            clockedin_msg = "You have successfully clocked in",
            clockedout = "You're off duty!",
            clockedout_msg = "You have successfully clocked out",
            callreq = "You must have a callsign",
        },
        searchchar = {
            title = "Civilian Search",
            col_fname = "Firstname",
            ph_fname = "John",
            col_lname = "Lastname",
            ph_lname = "Doe",
            col_gender = "Gender",
            col_gender_m = "Male",
            col_gender_f = "Female",
            col_gender_n = "Not available",
            search = "Search",
            result = "Result",
            results = "Results",
            found = "Found",
            back = "Back",
            close = "Close",
            feedback_1 = "Gender field not filled!",
            feedback_2 = "There must be at least one name field filled!",
            feedback_3 = "There was an error finding this person. Try again later",
            feedback_4 = "No results were found.",
            feedback_5 = "An error has occured. Try again later",
        },
        searchplate = {
            title = "Plate Search",
            col_plate = "License Plate",
            search = "Search",
            result = "Result",
            results = "Results",
            found = "Found",
            back = "Back",
            close = "Close",
            feedback_1 = "The required field were not filled",
            feedback_2 = "There was an error searching this plate. Try again later",
            feedback_3 = "No results found. Vehicle possibly stolen!",
            feedback_4 = "An error has occured. Try again later",
        },
        selectofficer = {
            title = "Select an officer",
            search = "Search",
            col_call = "Callsign",
            col_name = "Name",
            ph_name = "Name",
            col_action = "Actions",
            none = "None",
            select = "Select",
            clear = "Clear",
            close = "Close",
        },
        settings = {
            title = "Settings",
            category_1 = "Notifications",
            category_2 = "Notification sounds",
            play = "Play",
            notif_1 = "Notification Sound 1",
            notif_2 = "Notification Sound 2",
            notif_3 = "Notification Sound 3",
            category_3 = "Notification volume",
            category_4 = "Panic volume",
            category_5 = "Notification alert sound",
            alert_1 = "Person goes on duty",
            alert_2 = "Person goes off duty",
            alert_3 = "New bolo/warrant entry",
            category_6 = "Miscellaneous",
            category_7 = "Keybind configuration",
            set = "Set",
            assignkey = "Assign a key",
            defaultkey = "Default",
            save = "Save",
            close = "Close",
            error = "Keybind cannot be set",
            error_msg = "This keybind is unavailable!",
            saved = "Settings saved",
            saved_msg = "Your changes were saved!",
            sound = "Notification sound",
        },
        shiftactivity = {
            title = "Viewing shift log",
            statistics = "Statistics",
            shift_log = "Shift Log",
            ["24hrs"] = "Last 24 hours",
            ["7days"] = "Last 7 days",
            total = "Total",
            col_1 = "ID",
            col_2 = "Clock-in",
            col_3 = "Clock-out",
            col_4 = "Duration",
            no_results = "No results found",
            close = "Close",
        },
        addimage = {
            title = "Add an image",
            label = "Image label",
            placeholder = "Car wreck evidence",
            ['or'] = "OR",
            takepicture = "Take a picture with your phone",
            link = "Link",
            add = "Add",
            confirm_msg = "Do you want to submit this image?",
            discard = "Discard",
            confirm = "Confirm",
            close = "Close",
            feedback_1 = "Label required",
            feedback_1_msg = "Please enter a label for the image before submitting one",
            error_1 = "An error has occured",
            error_1_msg = "There was an issue processing your image, try again later.",
            feedback_2 = "The link entered was not a valid image",
            error_2 = "Invalid image",
            error_2_msg = "The imported image was not valid",
            feedback_3 = "An image could not be recieved from this link",
            error_3 = "Image could not be fetched",
            error_3_msg = "The image could not be recieved",
        },
        viewimage = {
            title = "Viewing attached image",
            close = "Close",
        },
        viewnotif = {
            title = "View all notifications",
            timeago = "ago",
            delete = "Delete",
            clear = "Clear all",
            alert = "Notifications cleared",
            alert_msg = "Your notifications were cleared",
            close = "Close",
        },
        addrelation = {
            title = "Add a relation",
            col_name = "Name",
            ph_name = "John Doe",
            col_relation = "Relation",
            ph_relation = "Spouse",
            add = "Add",
            close = "Close",
            feedback = "This required field was not filled",
        },
        criminalcode = {
            title = "Criminal Code",
            nocrimcode = "No criminal code was found",
            search = "Search",
            placeholder = "Offense name search",
            col_offense = "Offense",
            col_class = "Classification",
            col_pun = "Punishment",
            col_des = "Description",
            col_act = "Action",
            select = "Select",
            count = "Count",
            close = "Close",
        },
        selectpolice = {
            title = "Select Law Enforcement Involved",
            search = "Search",
            placeholder = "Name",
            col_call = "Callsign",
            col_name = "Name",
            col_act = "Action",
            select = "Select",
            none = "None",
            remove = "Remove",
            save = "Save",
            clear = "Clear all",
            close = "Close",
            ['and'] = "and", -- Used for grammar such as: one, two, AND three
        },
        editreport = {
            title_1 = "Editing incident report",
            title_2 = "Editing arrest report",
            col_ref = "Reference Number:",
            col_date = "Date registered:",
            col_sub = "Submitted by:",
            col_name = "Subject name",
            ph_name = "Select a subject",
            col_inres = "Incident result",
            ph_inres = "Select the result of the incident",
            col_location_1 = "Location of incident",
            col_location_2 = "Location of arrest",
            ph_location = "Paleto Dr.",
            col_des = "Brief description",
            ph_des = "Felony Speeding (30+ MPH)",
            col_leo = "Law enforcement involved",
            ph_leo = "Select all that apply or manually type it in",
            col_people = "Individuals involved",
            ph_people = "John Doe",
            col_vehicles = "Vehicles involved",
            ph_vehicles = "Benefactor Panto | Plate: 49HAP060",
            col_evidence = "Evidence found/confiscated",
            ph_evidence = "Phone | Confiscated",
            col_charges = "Charges",
            ph_charges = "Select what the charges will be for this individual",
            warning = "Adding or removing charges will not change the total fine or jail amounts!",
            col_fines = "Total fines",
            col_due = "Days to pay fine",
            ph_due = "7",
            col_finereduc = "Fine reductions",
            ph_finereduc = "No reduction",
            col_jail = "Total jail time",
            col_jailreduc = "Jail time reductions",
            ph_jailreduc = "No reduction",
            col_details = "Detailed report",
            ph_details = "Enter a detailed report of the incident",
            col_imgs = "Attached images",
            attchimg = "Attach an image",
            img_info = "Attach an image by importing via link or using your phone",
            img_del = "Are you sure you want to delete this image?",
            add = "Add",
            discard = "Discard changes",
            save = "Save",
            select = "Select",
            saved = "Changes saved",
            saved_msg = "Your changes were saved! These changes cannot be undone",
        },
        viewcharprofile = {
            title = "'s Profile", -- Name comes first, so it ends up looking like this "Gary's Profile"
            no_photo = "No photo identification on record",
            add_photo = "Add photo identification",
            photo_id = "Photo Identification",
            replace = "Replace",
            delete = "Delete",
            exempt = "Exempt",
            exempted = "Exempted",
            notes = "Notes",
            ph_notes = "Notes...",
            save = "Save",
            general = "General Data",
            col_fname = "First name",
            col_lname = "Last name",
            col_gender = "Gender",
            col_dob = "Date of Birth",
            col_war = "Warrant Status",
            col_bolo = "BOLO Status",
            active_bolo = "Active",
            contact = "Contact Information",
            edit = "Edit",
            col_phone = "Phone Number",
            col_adr = "Address",
            ph_none = "None in record",
            col_related = "Related to",
            col_name = "Name",
            col_relation = "Relation",
            add = "Add",
            no_results = "No results found",
            vehicles = "Registered Vehicles",
            col_plate = "Plate",
            col_vbolo = "Bolo Status",
            col_act = "Actions",
            no_bolo = "Clear",
            license_record = "Licenses & Records",
            cat_lic = "Registered Licenses",
            cat_fines = "Unpaid fines",
            cat_record = "Priors / Record",
            col_lictype = "License Type",
            unknown_license = "Unknown",
            col_id = "ID",
            col_fine = "Fine",
            col_dateoffense = "Date of Offense",
            col_due = "Due date",
            view = "View",
            col_type = "Type",
            col_ref = "Reference",
            col_date = "Date",
            back = "Back",
            img_del = "Are you sure you want to delete this image?",
            revoke = "Revoke",
            error_1 = "Vehicle profile could not be processed",
            error_1_msg = "There was an issue fetching a profile for this vehicle",
            saved = "Changes saved",
            saved_msg = "Your changes were saved successfully",
            error_2 = "An error has occured",
            error_msg = "There was an issue while fetching this report, try again later",
            revoked = "License revoked!",
            revoked_msg = "The license was revoked successfully",
            img_deleted = "Changes saved",
            img_deleted_msg = "The image has been deleted successfully",
            submitted = "Changes saved",
            submitted_msg = "Your image entry was saved successfully",
            fine_exe = "Are you sure you want to exempt this fine? This will exempt this person from having to pay this fine. This action cannot be undone!",
            fine_exempted = "Fine exepted",
            fine_exempted_msg = "The fine has been exempted successfully!",
            tooltip_1 = "Replace current photo",
            tooltip_2 = "Delete current photo",
            tooltip_3 = "Open profile",
            grant_lic = "Grant license",
            grant = "Grant",
            granted = "Granted",
            granted_success = "License granted",
            granted_success_msg = "The license has been granted successfully",
            granted_error = "An error has occured",
            granted_error_msg = "The license was not able to be granted. The player must be online to grant their license",
            close = "Close",
        },
        viewreport = {
            title_1 = "View incident report",
            title_2 = "View arrest report",
            col_ref = "Reference Number:",
            col_date = "Date registered:",
            col_sub = "Submitted by:",
            col_name = "Subject name",
            col_inres = "Incident result",
            col_location_1 = "Location of incident",
            col_location_2 = "Location of arrest",
            col_des = "Brief description",
            col_leo = "Law enforcement involved",
            col_people = "Individuals involved",
            col_vehicles = "Vehicles involved",
            col_evidence = "Evidence found/confiscated",
            col_charges = "Charges",
            col_fines = "Total fines",
            col_due = "Days to pay fine",
            col_finereduc = "Fine reductions",
            col_jail = "Total jail time",
            col_jailreduc = "Jail time reductions",
            col_details = "Detailed report",
            col_imgs = "Attached images",
            no_imgs = "No images were attached",
            edit = "Edit",
            save = "Save",
            delete = "Delete",
            none = "None",
            back = "Back",
            warning = "You will be permanently deleting this report from the database, are you sure?",
            editing = "You are now editing",
            editing_msg = "You can now make changes to this report. All changes will be documented. Once changes are saved, they cannot be undone!",
        },
        viewvehprofile = {
            title = "Vehicle Profile -",
            no_photo = "No photo on record",
            add_photo = "Add photo",
            photo = "Vehicle Photo",
            replace = "Replace",
            delete = "Delete",
            edit = "Edit",
            save = "Save",
            notes = "Notes",
            ph_notes = "Notes...",
            owner_info = "Owner Information",
            col_fname = "Firstname",
            col_lname = "Lastname",
            col_gender = "Gender",
            col_dob = "Date of Birth",
            col_war = "Warrant Status",
            col_bolo = "BOLO Status",
            veh_info = "Vehicle Information",
            col_plate = "Plate",
            col_model = "Model",
            col_color = "Color",
            ph_none = "None in record",
            back = "Back",
            active_bolo = "Active",
            no_bolo = "Clear",
            delete_img = "Are you sure you want to delete this image?",
            saved = "Changes saved",
            saved_msg = "Your changes were saved successfully",
            submitted = "Changes saved",
            submitted_msg = "Your image entry was saved successfully",
            tooltip_1 = "Replace current photo",
            tooltip_2 = "Delete current photo",
            tooltip_3 = "Open profile",
        },
        createreport = {
            title_1 = "Submit an incident report",
            title_2 = "Submit an arrest report",
            col_name = "Subject name",
            ph_name = "Select a subject",
            col_inres = "Incident result",
            ph_inres = "Select the result of the incident",
            col_location_1 = "Location of incident",
            col_location_2 = "Location of arrest",
            ph_location = "Paleto Dr.",
            col_des = "Brief description",
            ph_des = "Felony Speeding (30+ MPH)",
            col_leo = "Law enforcement involved",
            ph_leo = "Select all that apply or manually type it in",
            col_people = "Individuals involved",
            ph_people = "- John Doe",
            col_vehicles = "Vehicles involved",
            ph_vehicles = "Benefactor Panto | Plate: 49HAP060",
            col_evidence = "Evidence found/confiscated",
            ph_evidence = "Phone | Confiscated",
            col_charges = "Charges",
            ph_charges = "Select what the charges will be for this individual",
            warning = "Fine amounts or jail times cannot be changed after the report is submitted",
            col_fines = "Total fines",
            col_due = "Days to pay fine",
            ph_due = "7",
            col_finereduc = "Fine reductions",
            ph_finereduc = "No reduction",
            no_finereduc = "No fines to reduce",
            col_jail = "Total jail time",
            jail_btn = "Send suspect to jail automatically after submitting report",
            col_jailreason = "Jail reason",
            ph_jailreason = "First Degree Murder x2",
            col_jailreduc = "Jail time reductions",
            ph_jailreduc = "No reduction",
            no_jailreduc = "No jail time to reduce",
            col_details = "Detailed report",
            ph_details = "Enter a detailed report of the incident",
            ph_optional = "(Optional)",
            col_imgs = "Attached images",
            attch_img = "Attach an image",
            img_info = "Attach an image by importing via link or using your phone",
            img_del = "Are you sure you want to delete this image?",
            add = "Add",
            discard = "Discard changes",
            save = "Save",
            select = "Select",
            saved = "Changes saved",
            saved_msg = "Your changes were saved! These changes cannot be undone",
            error_1 = "Invalid input entry",
            error_1_msg = "You cannot set this field to 0. However, you can apply jail time reductions to 0!",
            error_2 = "Invalid input entry",
            error_2_msg = "You cannot set this field to 0. However, you can apply fine reductions to 0!",
            error_3 = "Incompleted input fields",
            error_3_msg = "There is one or more required input field not filled in!",
            error_4 = "Incompleted input fields",
            error_4_msg = "You must fill out a jail reason when automatically jailing someone!",
            error_5 = "Input field should only have numbers",
            error_5_msg = "The \"days to pay fine\" field should include only numbers!",
            submitted = "Report submitted",
            submitted_msg = "Your report has been submitted successfully!",
            fine_money = "$",
            fine_reduction = "Reduced to $",
            jail_reduction_1 = "Reduced to",
            jail_reduction_2 = "Months",
            jail_reduc_none = "No reduction |",
            jail_reduc_format = "Months",
            jail_reduc = "reduction |",
            fine_reduc_none = "No reduction | $",
            fine_reduc = "reduction | $",
        },
        activeunitstable = {
            police = "Police",
            ems = "EMS/Fire",
            roadside = "Roadside Assistance",
            col_call = "Callsign",
            col_name = "Name",
            col_status = "Status",
            col_act = "Actions",
            no_units = "No units available",
            tooltip_1 = "Set waypoint to location",
            tooltip_2 = "Copy patrol status",
            tooltip_3 = "Edit patrol status",
            sts_changed = "Status change",
            sts_changed_msg = "Status was successfully changed to",
            nav_set = "Navigation Set",
            nav_set_msg = "Your navigation has been updated",
        },
        bolotable = {
            voi = "Vehicles of Interest",
            poi = "People of Interest",
            war = "Warrants",
            col_ref = "Reference Number",
            col_model = "Model & Make",
            col_plate = "Plate",
            col_lseen = "Last Seen",
            col_act = "Actions",
            col_name = "Name",
            view = "View",
            no_results = "No results found",
            delete_bolo_warning = "You will be permanently deleting this BOLO from the active registry, are you sure?",
            delete_warrant_warning = "You will be permanently deleting this warrant from the active registry, are you sure?",
            deleted = "Entry deleted",
            deleted_msg = "The entry has been deleted successfully!",
        },
        createbolo = {
            title_1 = "Register a warrant",
            title_2 = "Register a vehicle of interest",
            title_3 = "Register a person of interest",
            col_model = "Vehicle Model",
            ph_model = "Benefactor Panto",
            col_plate = "License Plate",
            ph_plate = "49HAP060",
            col_color = "Vehicle Color",
            ph_color = "Red",
            col_lseen = "Last Seen",
            ph_lseen = "East-bound vespucci blvd",
            col_vdetails = "Vehicle Details",
            ph_vdetails = "Has a black spoiler, tinted windows, and red neon lights",
            col_reason = "Reason for interest",
            ph_reason = "Federal Bank Robbery, Fleeing and Eluding, Hostage Taking",
            col_notes = "Notes",
            ph_notes_veh = "The owner of the vehicle is agressive and was last seen with a firearm, beware.",
            ph_notes_bolo = "This individual was seen with multiple other individuals with the same style apparel and firearms, beware.",
            col_name = "Name",
            ph_name = "Select a subject",
            col_des = "Description",
            ph_des = "All black apparel with a white ski mask",
            discard = "Discard",
            submit = "Submit",
            select = "Select",
            feedback = "This required field was not filled",
        },
        store_users = {
            year = " year",
            years = " years",
            month = " month",
            months = " months",
            day = " day",
            days = " days",
            hour = " hour",
            hours = " hours",
            minute = " minute",
            minutes = " minutes",
            second = " second",
            seconds = " seconds",
            status_unavail = "Unavailable",
            status_avail = "Available",
            status_busy = "Busy",
            status_oncall = "On Call",
            status_intran = "In Transport",
            status_panic = "Panic",
        },
        confirmation = {
            title = "Are you sure?",
            no = "No",
            yes = "Yes",
        },
    },
}